project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: false

website:
  page-navigation: true
  title: Cloud-Optimized Geospatial Formats Guide
  repo-url: https://github.com/cloudnativegeo/cloud-optimized-geospatial-formats-guide
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    center: '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>. <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1">'
    left: '&copy; [Cloud-Native Geospatial Foundation](https://cloudnativegeo.org/), 2023'
  sidebar:
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/cloudnativegeo/cloud-optimized-geospatial-formats-guide
        text: "Cloud-Optimized Geospatial Formats Guide"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - href: overview.qmd
        text: Overview Slides
      - section: Formats
        contents:
        - section: Cloud Optimized GeoTIFFs (COG)
          contents:
          - cloud-optimized-geotiffs/intro.qmd
          - cloud-optimized-geotiffs/cogs-details.qmd
          - cloud-optimized-geotiffs/cogs-examples.ipynb
          - cloud-optimized-geotiffs/cogs-overview_resampling.ipynb
        - section: Zarr
          contents:
          - zarr/intro.qmd
          - zarr/zarr-in-practice.ipynb
        - section: Kerchunk
          contents:
          - kerchunk/intro.qmd
          - kerchunk/kerchunk-in-practice.ipynb
        - section: Cloud-Optimized HDF5 and NetCDF
          contents:
            - cloud-optimized-netcdf4-hdf5/index.qmd
        - section: Cloud-Optimized Point Clouds (COPC)
          contents:
            - copc/index.qmd
            - copc/lidar-las-to-copc.ipynb
        - section: GeoParquet
          contents:
            - geoparquet/index.qmd
            - geoparquet/geoparquet-example.ipynb
        - section: FlatGeobuf
          contents:
            - flatgeobuf/intro.qmd
            - flatgeobuf/hilbert-r-tree.qmd
            - flatgeobuf/flatgeobuf.ipynb
            - flatgeobuf/flatgeobuf-in-js.qmd
        - section: PMTiles
          contents:
            - pmtiles/intro.qmd
      - href: glossary.qmd
        text: Glossary
      - href: cookbooks/index.qmd
        text: Cookbooks
      - href: contributing.qmd
        text: Get Involved

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
    grid:
      sidebar-width: 400px


filters:
  - include-files.lua
  - quarto

resources:
  - CNAME
